### ISSUE TITLE
AngularJS data service design

### ISSUE THREAD

**Issue by tothandras** [tothandras/buildbot#2]
# AngularJS data service design

The purpose of this document is to start a conversation about the new frontend AngularJS data service, which will handle the communication with the backend.
### Responsibility
- Initial GET requests
- Maintaining data changes over WebSocket connection (eg. keep-alive)
- Caching
- Data sharing between tabs
- Use observables
- $http, RxJS, LocalStorage, ...

For UI: loading, lost connection events and more.
### API

``` coffeescript
# return an observable
bbDataService.getXXX().subscribe(onSuccess, onError, onComplete)

# get initial data and watch for changes
bbDataService.getXXXStream().subscribe(onSuccess, onError, onComplete)

# get all
bbDataService.getXXX()
  .subscribe (XXX) => @XXX = XXX
  , (error) => $log.debug(error)

# get one with ID and watch for changes
xxx = bbDataService.getXXX(id)
  .subscribe (XXX) => 
    @XXX = XXX
    bbDataService.getYYY(XXX.id)
      .subscribe (YYY) => XXX.YYY = YYY

# no more updates
xxx.dispose()

# use query
# TODO
```
### Sources
- [ng-vegas | Keynote: Beyond ngResource: The future of data in Angular](https://youtu.be/Bm3eDgZZMFs)
- [AngularJS Utah | Getting the most out of $http and Intro to rxjs](https://youtu.be/3I99MjfRPbc)
- [Integrate Angular.js with RxJS](https://xgrommx.github.io/rx-book/content/how_do_it/angular_with_rxjs.html)
- [Observable from WebSocket](https://xgrommx.github.io/rx-book/content/rxjs_bindings/dom/web_sockets/from_web_socket.html)

**Comment by tothandras** [comment]
I have started to wrote down my ideas, I will update this document as I progress to the next steps.
@tardyp, @shanzi

**Comment by shanzi** [comment]
Mark. 

It seems that you'd like every where that are using an object to subscribe and listen the changes. Is there any way to just update the object and let the Angular to update the view automatically?

**Comment by tothandras** [comment]
yes, it's possible. I tried that and it works. the service can return an
object and change the same object (same reference), the view will change (
something like .getXXX().getArray()) . I would keep this observer too,
because you can change the object (add fields, get correspondig data)
before using it. it's quite like the baby of promises :) .

**Comment by tardyp** [comment]
I don't really see the point of using observables.
AngularJS already has $watch I think this is a sufficient semantic for our usecases.

Having two way of observing data changes sounds incorrect for me.
I'd like you to look at the pages that are already done, and explain how they will be better written using rxjs?

**Comment by tothandras** [comment]
I couldn't find a page using angular & rxjs just yet. I just got so excited when I saw the presentation, because that's exactly what I was looking for. :)
The bad thing that we have to use $scope.$watch either way and the rx.angular.js helper library looks quite bad to me. So you are right, it's probably makes it unnecessary complicated.
